# Generated by Django 2.2.28 on 2022-12-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresswapkdpzazp'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresswapkdpzazp',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
